name: PHP Composer

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6

    - name: coverage
      run: composer run coverage

    - name: coverage-badge
      uses: timkrase/phpunit-coverage-badge@v1.2.1
      with:
        report: tests/report/clover.xml
        coverage_badge_path: output/coverage.svg
        push_badge: true
        repo_token: ${{secrets.GITHUB_TOKEN}}
